# The URL the site will be built for
base_url = "https://interkinactive.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
nav = [
  # { name = "Produkte", url = "/", new_tab = false},
  { name = "Shop", url = "https://www.etsy.com/de/shop/Interkinactive", new_tab = true},
  # { name = "Creative Coding", url = "/blog/", new_tab = false},
  { name = "About", url = "/about-me/", new_tab = false},
  { name = "Kontakt", url = "/contact/", new_tab = false}
]
# Put all your custom variables here

[extra.author]
name = "Jessica Stürmer"
